name: "SSVM"
on:
  pull_request:
    branches: [ ssvm ]
  push:
    branches: [ ssvm ]
jobs:
  ssvm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Submodules
      run: git submodule update --init --recursive
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-shell --run "cargo test"
